### ISSUE TITLE
Installation test class failure

### ISSUE THREAD

**Issue by jjrudio** [kumarrk21/S1PageLayouts#1]
Stack Trace: Class.S1PageLayoutCompController.getObj: line 71, column 1 Class.S1PageLayoutCompControllerTest.test_method_one: line 11, column 1 

Error while installing in our Salesforce org. Any idea how to solve this?
Any ideas or help is highly appreciated. Thank you.

**Comment by kumarrk21** [comment]
Not sure why the test class is failing in your org (assuming it's Sandbox/Developer org). Try creating the classes manually in your org and run the test classes to see why it's failing.
